test: &default

  # Credentials for REST APIs
  client_id: ASEj5xBDgH09_34gfBrwNhf6kHyU7LqMpr3YgBUpAlejR0o1WAk5F6l7lTcw
  client_secret: EKJLuBDqmVHAZv9UTpoy9_zVNbdgISieu_4t4kQNDi8Vs4gZoyeA6wuznwsE

  # Mode can be 'live' or 'sandbox'
  mode: sandbox

  # Credentials for Classic APIs
  # Sandbox test AppID:
    #APP-80W284485P519543T
  app_id: APP-80W284485P519543T
  username: seller-account-merchant_api1.test.com
  password: GDYBWYPPDMZU6SWJ
  signature: AFcWxV21C7fd0v3bYYYRCpSSRl31AB2SLOKPCoWOO0WEaJ7Ec80OpVi6
  # # With Certificate
  # cert_path: "config/cert_key.pem"
  sandbox_email_address: seller-account-merchant@test.com

  # # IP Address
  # ip_address: 127.0.0.1
  # # HTTP Proxy
  # http_proxy: http://proxy-ipaddress:3129/

development:
  <<: *default

production:
  <<: *default
  mode: live
